# PostgreSQL. Versions 7.4 and 8.x are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
development:
  adapter: postgresql
  encoding: unicode
  database: sandpit_development
  pool: 5
  username: postgres
  password: september
  # Set the schema_search_path in order to use the rake task 'rake db:schema:dump' to update the schema.rb file content
  # and to include the table/index definitions from the template subdomain schema.
  # NB: the user option is required in order for the task to pick up the template subdomain schema indexes.
  #schema_search_path: "\"$user\",public,template"

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost
  #port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # The server defaults to notice.
  #min_messages: warning

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: postgresql
  encoding: unicode
  database: sandpit_test
  pool: 5
  username: postgres
  password: september

production:
  adapter: postgresql
  encoding: unicode
  database: sandpit_production
  pool: 5
  username: postgres
  password: september
